package main;

public enum TokenType {
    // VARIABLES
    VAR,

    // LOOPS
    FOR, WHILE,

    // CONDITIONALS
    IF, ELSE,

    // IDENTIFIERS
    IDENTIFIER, NUMBER, CHAR_LITERAL, STRING_LITERAL,
    FLOAT_LITERAL, BOOL_LITERAL, DOUBLE_LITERAL,

    // OPERATORS
    IS_EQUALS, EQUALS, ADD, SUBSTRAIN, DIVIDE, MULTIPLY, MODULE,

    // SEPARATORS
    SEMICOLON, COMMA, LEFT_PAREN, RIGHT_PAREN,
    // ; , ( ) { } : .
    LEFT_BRACE, RIGHT_BRACE, COLON, DOT,

    //LOGIC OPERATORS
    GREATER_THAN, LESS_THAN,

    // FUNCTIONS
    PRINT,
    RETURN, 
    ASSEMBLYDEBUG,
    
    // COMMENTS
    COMMENTS,

    // END OF LINE
    END_OF_FILE
}
